export const students = [
  {
    id: "2d154321",
    student_id: "2d154321",
    admission_id: "A0001",
    pen: "528fa609",
    apaar: "3eb6fea3",
    adhaar: "1234-4567-1234",
    admission_date: "2021-09-22",
    admission_catagory: "staff_ward",
    admission_scheme: "non-rte",
    discount: "0",
    cast: "gen",
    is_active: "active",
    transport_details: {
      mode: "School-Transport",
      vehicle_id: "5g13300",
      stop_name: "Pokhraha",
    },
    personal_details: {
      name: "Diane Lowe 1",
      height: "143",
      blood_group: "O+",
      correspondence_address: {
        addressline1: "828 Barrows Mill",
        addressline2: "Suite 678",
        city: "Yesseniafurt",
        state: "New Hampshire",
        pincode: "83103-6068",
      },
      permanent_address: {
        addressline1: "p828 Barrows Mill",
        addressline2: "pSuite 678",
        city: "pYesseniafurt",
        state: "pNew Hampshire",
        pincode: "p83103-6068",
      },
      dob: "2005-10-30",
      gender: "male",
    },
    guardian_details: {
      name: "Amy Rath",
      relation: "Father",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "George_Bergnaum83@yahoo.com",
      education: "Graduate",
    },
    father_details: {
      name: "Tom",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "tom_bernard83@yahoo.com",
      education: "PG",
    },
    mother_details: {
      name: "Kristine",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "kristine123@yahoo.com",
      education: "Graduate",
    },
    previous_school: {
      name: "M.K D.A.V Public School",
      marks: {
        maths: "56",
        hindi: "67",
        english: "70",
        science: "65",
        computer: "80",
      },
    },
  },
  {
    id: "2d154322",
    student_id: "2d154322",
    admission_id: "A0002",
    pen: "528fa609",
    apaar: "3eb6fea3",
    adhaar: "1234-4567-1234",
    admission_date: "2021-09-22",
    admission_catagory: "staff_ward",
    admission_scheme: "non-rte",
    discount: "0",
    cast: "gen",
    is_active: "active",
    transport_details: {
      mode: "School-Transport",
      vehicle_id: "5g13300",
      stop_name: "Pokhraha",
    },
    personal_details: {
      name: "Diane Lowe 2",
      height: "143",
      blood_group: "O+",
      correspondence_address: {
        addressline1: "828 Barrows Mill",
        addressline2: "Suite 678",
        city: "Yesseniafurt",
        state: "New Hampshire",
        pincode: "83103-6068",
      },
      permanent_address: {
        addressline1: "p828 Barrows Mill",
        addressline2: "pSuite 678",
        city: "pYesseniafurt",
        state: "pNew Hampshire",
        pincode: "p83103-6068",
      },
      dob: "2005-10-30",
      gender: "male",
    },
    guardian_details: {
      name: "Amy Rath",
      relation: "Father",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "George_Bergnaum83@yahoo.com",
      education: "Graduate",
    },
    father_details: {
      name: "Tom",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "tom_bernard83@yahoo.com",
      education: "PG",
    },
    mother_details: {
      name: "Kristine",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "kristine123@yahoo.com",
      education: "Graduate",
    },
    previous_school: {
      name: "M.K D.A.V Public School",
      marks: {
        maths: "56",
        hindi: "67",
        english: "70",
        science: "65",
        computer: "80",
      },
    },
  },
  {
    id: "2d154323",
    student_id: "2d154323",
    admission_id: "A0003",
    pen: "528fa609",
    apaar: "3eb6fea3",
    adhaar: "1234-4567-1234",
    admission_date: "2021-09-22",
    admission_catagory: "staff_ward",
    admission_scheme: "non-rte",
    discount: "0",
    cast: "gen",
    is_active: "active",
    transport_details: {
      mode: "School-Transport",
      vehicle_id: "5g13300",
      stop_name: "Pokhraha",
    },
    personal_details: {
      name: "Diane Lowe 3",
      height: "143",
      blood_group: "O+",
      correspondence_address: {
        addressline1: "828 Barrows Mill",
        addressline2: "Suite 678",
        city: "Yesseniafurt",
        state: "New Hampshire",
        pincode: "83103-6068",
      },
      permanent_address: {
        addressline1: "p828 Barrows Mill",
        addressline2: "pSuite 678",
        city: "pYesseniafurt",
        state: "pNew Hampshire",
        pincode: "p83103-6068",
      },
      dob: "2005-10-30",
      gender: "male",
    },
    guardian_details: {
      name: "Amy Rath",
      relation: "Father",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "George_Bergnaum83@yahoo.com",
      education: "Graduate",
    },
    father_details: {
      name: "Tom",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "tom_bernard83@yahoo.com",
      education: "PG",
    },
    mother_details: {
      name: "Kristine",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "kristine123@yahoo.com",
      education: "Graduate",
    },
    previous_school: {
      name: "M.K D.A.V Public School",
      marks: {
        maths: "56",
        hindi: "67",
        english: "70",
        science: "65",
        computer: "80",
      },
    },
  },
  {
    id: "2d154324",
    student_id: "2d154324",
    admission_id: "A0004",
    pen: "528fa609",
    apaar: "3eb6fea3",
    adhaar: "1234-4567-1234",
    admission_date: "2021-09-22",
    admission_catagory: "staff_ward",
    admission_scheme: "non-rte",
    discount: "0",
    cast: "gen",
    is_active: "active",
    transport_details: {
      mode: "School-Transport",
      vehicle_id: "5g13300",
      stop_name: "Pokhraha",
    },
    personal_details: {
      name: "Diane Lowe 4",
      height: "143",
      blood_group: "O+",
      correspondence_address: {
        addressline1: "828 Barrows Mill",
        addressline2: "Suite 678",
        city: "Yesseniafurt",
        state: "New Hampshire",
        pincode: "83103-6068",
      },
      permanent_address: {
        addressline1: "p828 Barrows Mill",
        addressline2: "pSuite 678",
        city: "pYesseniafurt",
        state: "pNew Hampshire",
        pincode: "p83103-6068",
      },
      dob: "2005-10-30",
      gender: "male",
    },
    guardian_details: {
      name: "Amy Rath",
      relation: "Father",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "George_Bergnaum83@yahoo.com",
      education: "Graduate",
    },
    father_details: {
      name: "Tom",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "tom_bernard83@yahoo.com",
      education: "PG",
    },
    mother_details: {
      name: "Kristine",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "kristine123@yahoo.com",
      education: "Graduate",
    },
    previous_school: {
      name: "M.K D.A.V Public School",
      marks: {
        maths: "56",
        hindi: "67",
        english: "70",
        science: "65",
        computer: "80",
      },
    },
  },
];

export const students_empty = [
  {
    id: "",
    student_id: "",
    admission_id: "",
    pen: "",
    apaar: "",
    adhaar: "",
    admission_date: "",
    admission_catagory: "",
    admission_scheme: "",
    discount: "",
    cast: "",
    is_active: "",
    transport_details: {
      mode: "",
      stop_name: "",
      vehicle_id: "",
    },
    personal_details: {
      name: "",
      height: "",
      blood_group: "",
      correspondence_address: {
        addressline1: "",
        addressline2: "",
        city: "",
        state: "",
        pincode: "",
      },
      permanent_address: {
        addressline1: "",
        addressline2: "",
        city: "",
        state: "",
        pincode: "",
      },
      dob: "",
      gender: "",
    },
    guardian_details: {
      name: "",
      relation: "",
      occupation: "",
      contact: "",
      email: "",
    },
    father_details: {
      name: "",
      occupation: "",
      contact: "",
      email: "",
      education: "",
    },
    mother_details: {
      name: "",
      occupation: "",
      contact: "",
      email: "",
      education: "",
    },
    previous_school: {
      name: "",
      marks: {
        maths: "",
        hindi: "",
        english: "",
        science: "",
        computer: "",
      },
    },
  },
];
