export const students = [
  {
    id: "2d154374-84af-4578-8c3d-87c721be5c13",
    student_id: "7f2ef334-62e7-4cc7-93f3-988813e24497",
    admission_id: "482ab8a6-ea2e-4019-85b4-fb122b68abb1",
    pen: "528fa609-737f-4fdf-80d1-9890fc47537f",
    apaar: "3eb6fea3-2a69-49bd-b1f9-1daddb562e0e",
    adhaar: "1234-4567-1234",
    admission_date: "2021-09-22",
    admission_catagory: "staff_ward",
    admission_scheme: "non-rte",
    discount: "0",
    cast: "gen",
    is_active: "active",
    transport_details: {
      mode: "transport",
      stop_id: "2d154374",
      vehicle_no: "1",
    },
    personal_details: {
      name: "Diane Lowe",
      height: "143",
      blood_group: "O+",
      correspondence_address: {
        addressline1: "828 Barrows Mill",
        addressline2: "Suite 678",
        city: "Yesseniafurt",
        state: "New Hampshire",
        pincode: "83103-6068",
      },
      permanent_address: {
        addressline1: "p828 Barrows Mill",
        addressline2: "pSuite 678",
        city: "pYesseniafurt",
        state: "pNew Hampshire",
        pincode: "p83103-6068",
      },
      dob: "2005-10-30",
      gender: "male",
    },
    guardian_details: {
      name: "Amy Rath",
      relation: "Father",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "George_Bergnaum83@yahoo.com",
      education: "Graduate",
    },
    father_details: {
      name: "Tom",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "tom_bernard83@yahoo.com",
      education: "PG",
    },
    mother_details: {
      name: "Kristine",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "kristine123@yahoo.com",
      education: "Graduate",
    },
    previous_school: {
      name: "M.K D.A.V Public School",
      marks: {
        maths: "56",
        hindi: "67",
        english: "70",
        science: "65",
        computer: "80",
      },
    },
  },
];

export const students_empty = [
  {
    id: "",
    student_id: "",
    admission_id: "",
    pen: "",
    apaar: "",
    adhaar: "",
    admission_date: "",
    admission_catagory: "",
    admission_scheme: "",
    discount: "",
    cast: "",
    is_active: "",
    transport_details: {
      mode: "",
      stop_id: "",
      vehicle_no: "",
    },
    personal_details: {
      name: "",
      height: "",
      blood_group: "",
      correspondence_address: {
        addressline1: "",
        addressline2: "",
        city: "",
        state: "",
        pincode: "",
      },
      permanent_address: {
        addressline1: "",
        addressline2: "",
        city: "",
        state: "",
        pincode: "",
      },
      dob: "",
      gender: "",
    },
    guardian_details: {
      name: "",
      relation: "",
      occupation: "",
      contact: "",
      email: "",
    },
    father_details: {
      name: "",
      occupation: "",
      contact: "",
      email: "",
      education: "",
    },
    mother_details: {
      name: "",
      occupation: "",
      contact: "",
      email: "",
      education: "",
    },
    previous_school: {
      name: "",
      marks: {
        maths: "",
        hindi: "",
        english: "",
        science: "",
        computer: "",
      },
    },
  },
];
