export const teachers_data = [
  {
    id: "2d154374454",
    teacher_id: "2d154374454",
    tp_code: "528fa609",
    oasis_id: "3eb6fea3",
    adhaar: "1234-4567-1234",
    qualification: "Graduate",
    joining_date: "2021-09-22",
    admission_catagory: "Regular",
    type: "NTT",
    discount: "0",
    cast: "gen",
    is_active: "active",
    sub_post: "House Incharge",
    transport_details: {
      mode: "School-Transport",
      vehicle_id: "5g13300",
      stop_name: "Pokhraha",
    },
    personal_details: {
      name: "Diane Lowe",
      contact: "99605746874",
      height: "143",
      blood_group: "O+",
      correspondence_address: {
        addressline1: "828 Barrows Mill",
        addressline2: "Suite 678",
        city: "Yesseniafurt",
        state: "New Hampshire",
        pincode: "83103-6068",
      },
      permanent_address: {
        addressline1: "p828 Barrows Mill",
        addressline2: "pSuite 678",
        city: "pYesseniafurt",
        state: "pNew Hampshire",
        pincode: "p83103-6068",
      },
      dob: "2005-10-30",
      gender: "male",
    },
    guardian_details: {
      name: "Amy Rath",
      relation: "Father",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "George_Bergnaum83@yahoo.com",
      education: "Graduate",
    },
    father_details: {
      name: "Tom",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "tom_bernard83@yahoo.com",
      education: "PG",
    },
    mother_details: {
      name: "Kristine",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "kristine123@yahoo.com",
      education: "Graduate",
    },
  },
  {
    id: "2d154374455",
    teacher_id: "2d154374455",
    tp_code: "528fa609",
    oasis_id: "3eb6fea3",
    adhaar: "1234-4567-1234",
    qualification: "Graduate",
    joining_date: "2021-09-22",
    admission_catagory: "Regular",
    type: "NTT",
    discount: "0",
    cast: "gen",
    is_active: "active",
    sub_post: "House Incharge",
    transport_details: {
      mode: "School-Transport",
      vehicle_id: "5g13300",
      stop_name: "Pokhraha",
    },
    personal_details: {
      name: "Jane Dow",
      contact: "99605746874",
      height: "143",
      blood_group: "O+",
      correspondence_address: {
        addressline1: "828 Barrows Mill",
        addressline2: "Suite 678",
        city: "Yesseniafurt",
        state: "New Hampshire",
        pincode: "83103-6068",
      },
      permanent_address: {
        addressline1: "p828 Barrows Mill",
        addressline2: "pSuite 678",
        city: "pYesseniafurt",
        state: "pNew Hampshire",
        pincode: "p83103-6068",
      },
      dob: "2005-10-30",
      gender: "male",
    },
    guardian_details: {
      name: "Amy Rath",
      relation: "Father",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "George_Bergnaum83@yahoo.com",
      education: "Graduate",
    },
    father_details: {
      name: "Tom",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "tom_bernard83@yahoo.com",
      education: "PG",
    },
    mother_details: {
      name: "Kristine",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "kristine123@yahoo.com",
      education: "Graduate",
    },
  },
  {
    id: "2d154374456",
    teacher_id: "2d154374456",
    tp_code: "528fa609",
    oasis_id: "3eb6fea3",
    adhaar: "1234-4567-1234",
    qualification: "Graduate",
    joining_date: "2021-09-22",
    admission_catagory: "Regular",
    type: "NTT",
    discount: "0",
    cast: "gen",
    is_active: "active",
    sub_post: "House Incharge",
    transport_details: {
      mode: "School-Transport",
      vehicle_id: "5g13300",
      stop_name: "Pokhraha",
    },
    personal_details: {
      name: "Mary James",
      contact: "99605746874",
      height: "143",
      blood_group: "O+",
      correspondence_address: {
        addressline1: "828 Barrows Mill",
        addressline2: "Suite 678",
        city: "Yesseniafurt",
        state: "New Hampshire",
        pincode: "83103-6068",
      },
      permanent_address: {
        addressline1: "p828 Barrows Mill",
        addressline2: "pSuite 678",
        city: "pYesseniafurt",
        state: "pNew Hampshire",
        pincode: "p83103-6068",
      },
      dob: "2005-10-30",
      gender: "male",
    },
    guardian_details: {
      name: "Amy Rath",
      relation: "Father",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "George_Bergnaum83@yahoo.com",
      education: "Graduate",
    },
    father_details: {
      name: "Tom",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "tom_bernard83@yahoo.com",
      education: "PG",
    },
    mother_details: {
      name: "Kristine",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "kristine123@yahoo.com",
      education: "Graduate",
    },
  },
];

export const teachers_empty = [
  {
    id: "",
    teacher_id: "",
    tp_code: "",
    oasis_id: "",
    adhaar: "",
    joining_date: "",
    admission_catagory: "",
    type: "",
    discount: "0",
    cast: "",
    is_active: "",
    sub_post: "",
    transport_details: {
      mode: "",
      stop_name: "",
      vehicle_id: "",
    },
    personal_details: {
      name: "",
      height: "",
      blood_group: "",
      correspondence_address: {
        addressline1: "",
        addressline2: "",
        city: "",
        state: "",
        pincode: "",
      },
      permanent_address: {
        addressline1: "",
        addressline2: "",
        city: "",
        state: "",
        pincode: "",
      },
      dob: "",
      gender: "",
    },
    guardian_details: {
      name: "",
      relation: "",
      occupation: "",
      contact: "",
      email: "",
      education: "",
    },
    father_details: {
      name: "",
      occupation: "",
      contact: "",
      email: "",
      education: "",
    },
    mother_details: {
      name: "",
      occupation: "",
      contact: "",
      email: "",
      education: "",
    },
  },
];
