export const teachers = [
  {
    id: "2d154374454",
    teacher_id: "2d154374454",
    tp_code: "528fa609",
    oasis_id: "3eb6fea3",
    adhaar: "1234-4567-1234",
    admission_date: "2021-09-22",
    admission_catagory: "regular",
    type: ["NTT"],
    discount: "0",
    cast: "gen",
    is_active: "active",
    subject: ["2d154374", "5g13300"],
    sub_post: "House Incharge",
    transport_details: {
      mode: "transport",
      stop_name: "Pokhraha",
      vehicle_no: "JH 03AF 1234",
    },
    personal_details: {
      name: "Diane Lowe",
      height: "143",
      blood_group: "O+",
      correspondence_address: {
        addressline1: "828 Barrows Mill",
        addressline2: "Suite 678",
        city: "Yesseniafurt",
        state: "New Hampshire",
        pincode: "83103-6068",
      },
      permanent_address: {
        addressline1: "p828 Barrows Mill",
        addressline2: "pSuite 678",
        city: "pYesseniafurt",
        state: "pNew Hampshire",
        pincode: "p83103-6068",
      },
      dob: "2005-10-30",
      gender: "male",
    },
    guardian_details: {
      name: "Amy Rath",
      relation: "Father",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "George_Bergnaum83@yahoo.com",
      education: "Graduate",
    },
    father_details: {
      name: "Tom",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "tom_bernard83@yahoo.com",
      education: "PG",
    },
    mother_details: {
      name: "Kristine",
      occupation: "Others",
      contact: "513.896.3935 x01932",
      email: "kristine123@yahoo.com",
      education: "Graduate",
    },
  },
];

export const teachers_empty = [
  {
    id: "",
    teacher_id: "",
    tp_code: "",
    oasis_id: "",
    adhaar: "",
    admission_date: "",
    admission_catagory: "",
    type: [],
    discount: "0",
    cast: "",
    is_active: "",
    subject: [],
    sub_post: "",
    transport_details: {
      mode: "",
      stop_name: "",
      vehicle_no: "",
    },
    personal_details: {
      name: "",
      height: "",
      blood_group: "",
      correspondence_address: {
        addressline1: "",
        addressline2: "",
        city: "",
        state: "",
        pincode: "",
      },
      permanent_address: {
        addressline1: "",
        addressline2: "",
        city: "",
        state: "",
        pincode: "",
      },
      dob: "",
      gender: "",
    },
    guardian_details: {
      name: "",
      relation: "",
      occupation: "",
      contact: "",
      email: "",
      education: "",
    },
    father_details: {
      name: "",
      occupation: "",
      contact: "",
      email: "",
      education: "",
    },
    mother_details: {
      name: "",
      occupation: "",
      contact: "",
      email: "",
      education: "",
    },
  },
];
