export interface VimlaPandeyDataProps {
  photofile: File | undefined;
  studentFullName: string;
  studentDOB: string;
  studentGender: string;
  fatherName: string;
  fatherEduQual: string;
  fatherOccupation: string;
  fatherEmail: string;
  motherName: string;
  motherEduQual: string;
  motherOccupation: string;
  motherEmail: string;
  current_addressline1: string;
  current_addressline2: string;
  current_city: string;
  current_state: string;
  current_pincode: string;
  permanent_addressline1: string;
  permanent_addressline2: string;
  permanent_city: string;
  permanent_state: string;
  permanent_pincode: string;
  singleGirlChild: boolean | undefined;
  speciallyAbled: boolean | undefined;
  belongToEWS: boolean | undefined;
  catagory: "General" | "OBC" | "ST" | "SC" | "EWS" | "";
  adhaar: string;
  lastSchoolName: string;
  lastClassStudies: string;
  lastSchoolAffiliation: "CBSE" | "ICSE" | "IB" | "State_Board" | "";
  subject1: string;
  subject1_max_marks: string;
  subject1_marks_obtained: string;
  subject1_percentage: string;
  subject1_remarks: string;
  subject2: string;
  subject2_max_marks: string;
  subject2_marks_obtained: string;
  subject2_percentage: string;
  subject2_remarks: string;
  subject3: string;
  subject3_max_marks: string;
  subject3_marks_obtained: string;
  subject3_percentage: string;
  subject3_remarks: string;
  subject4: string;
  subject4_max_marks: string;
  subject4_marks_obtained: string;
  subject4_percentage: string;
  subject4_remarks: string;
  subject5: string;
  subject5_max_marks: string;
  subject5_marks_obtained: string;
  subject5_percentage: string;
  subject5_remarks: string;
  subject6: string;
  subject6_max_marks: string;
  subject6_marks_obtained: string;
  subject6_percentage: string;
  subject6_remarks: string;
  transfer_certificate_no: string;
  date_of_issue: string;
}
